/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAutocomplete: typeof import('./resources/ts/@core/components/app-form-elements/AppAutocomplete.vue')['default']
    AppDataTableServer: typeof import('./resources/ts/components/table/AppDataTableServer.vue')['default']
    AppDateTimePicker: typeof import('./resources/ts/@core/components/app-form-elements/AppDateTimePicker.vue')['default']
    AppDrawerHeaderSection: typeof import('./resources/ts/@core/components/AppDrawerHeaderSection.vue')['default']
    AppFormDrawer: typeof import('./resources/ts/components/form/AppFormDrawer.vue')['default']
    AppImageSlot: typeof import('./resources/ts/components/form/AppImageSlot.vue')['default']
    AppImageUpload: typeof import('./resources/ts/components/form/AppImageUpload.vue')['default']
    AppLoadingIndicator: typeof import('./resources/ts/components/AppLoadingIndicator.vue')['default']
    AppSelect: typeof import('./resources/ts/@core/components/app-form-elements/AppSelect.vue')['default']
    AppStepper: typeof import('./resources/ts/@core/components/AppStepper.vue')['default']
    AppTextarea: typeof import('./resources/ts/@core/components/app-form-elements/AppTextarea.vue')['default']
    AppTextField: typeof import('./resources/ts/@core/components/app-form-elements/AppTextField.vue')['default']
    AppToaster: typeof import('./resources/ts/components/AppToaster.vue')['default']
    AppVisitWindow: typeof import('./resources/ts/components/AppVisitWindow.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/ts/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CustomizerSection: typeof import('./resources/ts/@core/components/CustomizerSection.vue')['default']
    CustomRadios: typeof import('./resources/ts/@core/components/app-form-elements/CustomRadios.vue')['default']
    CustomRadiosWithIcon: typeof import('./resources/ts/@core/components/app-form-elements/CustomRadiosWithIcon.vue')['default']
    CustomRadiosWithImage: typeof import('./resources/ts/@core/components/app-form-elements/CustomRadiosWithImage.vue')['default']
    DialogCloseBtn: typeof import('./resources/ts/@core/components/DialogCloseBtn.vue')['default']
    ErrorHeader: typeof import('./resources/ts/components/ErrorHeader.vue')['default']
    Notifications: typeof import('./resources/ts/@core/components/Notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./resources/ts/@core/components/ScrollToTop.vue')['default']
    TablePagination: typeof import('./resources/ts/@core/components/TablePagination.vue')['default']
    TheCustomizer: typeof import('./resources/ts/@core/components/TheCustomizer.vue')['default']
    ThemeSwitcher: typeof import('./resources/ts/@core/components/ThemeSwitcher.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
