/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-admins': RouteRecordInfo<'admin-admins', '/admin/admins', Record<never, never>, Record<never, never>>,
    'admin-blog': RouteRecordInfo<'admin-blog', '/admin/blog', Record<never, never>, Record<never, never>>,
    'admin-categories': RouteRecordInfo<'admin-categories', '/admin/categories', Record<never, never>, Record<never, never>>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'admin-districts': RouteRecordInfo<'admin-districts', '/admin/districts', Record<never, never>, Record<never, never>>,
    'admin-governorates': RouteRecordInfo<'admin-governorates', '/admin/governorates', Record<never, never>, Record<never, never>>,
    'admin-legal-pages': RouteRecordInfo<'admin-legal-pages', '/admin/legal-pages', Record<never, never>, Record<never, never>>,
    'admin-orders': RouteRecordInfo<'admin-orders', '/admin/orders', Record<never, never>, Record<never, never>>,
    'admin-orders-id': RouteRecordInfo<'admin-orders-id', '/admin/orders/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-permissions': RouteRecordInfo<'admin-permissions', '/admin/permissions', Record<never, never>, Record<never, never>>,
    'admin-roles': RouteRecordInfo<'admin-roles', '/admin/roles', Record<never, never>, Record<never, never>>,
    'admin-services': RouteRecordInfo<'admin-services', '/admin/services', Record<never, never>, Record<never, never>>,
    'admin-settings': RouteRecordInfo<'admin-settings', '/admin/settings', Record<never, never>, Record<never, never>>,
    'admin-sliders': RouteRecordInfo<'admin-sliders', '/admin/sliders', Record<never, never>, Record<never, never>>,
    'admin-specializations': RouteRecordInfo<'admin-specializations', '/admin/specializations', Record<never, never>, Record<never, never>>,
    'admin-technician-applications': RouteRecordInfo<'admin-technician-applications', '/admin/technician-applications', Record<never, never>, Record<never, never>>,
    'admin-technician-applications-id': RouteRecordInfo<'admin-technician-applications-id', '/admin/technician-applications/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-technicians': RouteRecordInfo<'admin-technicians', '/admin/technicians', Record<never, never>, Record<never, never>>,
    'admin-technicians-id': RouteRecordInfo<'admin-technicians-id', '/admin/technicians/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'admin-users-id': RouteRecordInfo<'admin-users-id', '/admin/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-email-filter': RouteRecordInfo<'apps-email-filter', '/apps/email/:filter', { filter: ParamValue<true> }, { filter: ParamValue<false> }>,
    'apps-email-label': RouteRecordInfo<'apps-email-label', '/apps/email/:label', { label: ParamValue<true> }, { label: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
  }
}
